# Generated by Django 5.0.2 on 2024-02-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
