# Generated by Django 5.0.2 on 2024-02-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0002_remove_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
