# Generated by Django 5.0.2 on 2024-02-28 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0003_task_end_time_task_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
