# Generated by Django 5.0.2 on 2024-03-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_app', '0004_remove_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
    ]
